services:
  quantum-trust-database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - quantum-trust-network
    restart: always

  quantum-trust-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - /home/miluski/QuantumTrust/media:/media
      - /home/miluski/QuantumTrust/certs:/certs
    depends_on:
      - quantum-trust-database
    networks:
      - quantum-trust-network
    restart: always

  quantum-trust-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./certs:/etc/letsencrypt"
    depends_on:
      - certbot
    ports:
      - "443:443"
    networks:
      - quantum-trust-network
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: /bin/sh -c "certbot renew; sleep 12h & wait $${!};"
    restart: always

networks:
  quantum-trust-network:
    driver: bridge