services:
  quantum-trust-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quantum-trust-server
    depends_on:
      - quantum-trust-db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quantum-trust-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./backend/src:/src
  quantum-trust-db:
    image: 'postgres:latest'
    container_name: quantum-trust-db
    environment:
      POSTGRES_DB: compose-postgres
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  quantum-trust-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quantum-trust-frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - quantum-trust-server
    volumes: []
volumes:
  postgres_data: