services:
  quantum-trust-database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - quantum-trust-network
    restart: always

  quantum-trust-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9443:9443"
    volumes:
      - /home/miluski/QuantumTrust/media:/media
      - /home/miluski/QuantumTrust/certs:/certs
    depends_on:
      - quantum-trust-database
    networks:
      - quantum-trust-network
    restart: always

  quantum-trust-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - /home/miluski/QuantumTrust/media:/media
      - /home/miluski/QuantumTrust/certs:/etc/letsencrypt/live/quantum-trust.cc
    depends_on:
      - quantum-trust-backend
    networks:
      - quantum-trust-network
    restart: always

networks:
  quantum-trust-network:
    driver: bridge