services:
  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - certbot
    command: /bin/sh -c "while [ ! -f /etc/letsencrypt/live/quantum-trust.cc/fullchain.pem ]; do echo 'Waiting for certificates...'; sleep 1; done && nginx -g 'daemon off;'"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: /bin/sh -c "certbot renew; sleep 12h & wait $${!};"
    restart: always
