services:
  quantum-trust-server:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: quantum-trust-server
    depends_on:
      - quantum-trust-db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./src
  quantum-trust-db:
    image: 'postgres:latest'
    container_name: quantum-trust-db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
volumes:
  app:
