name: Continuous Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: End CD Early
      run: echo "Ending CD early" && exit 0

    - name: Deploy to Server
      if: always() 
      run: sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '/home/miluski/deploy.sh'