name: Continuous Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Create QuantumTrust folder and deploy.sh script
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
          mkdir -p /home/miluski/QuantumTrust &&
          if [ ! -f /home/miluski/QuantumTrust/deploy.sh ]; then
            echo "#!/bin/bash" > /home/miluski/QuantumTrust/deploy.sh &&
            echo "cd /home/miluski/QuantumTrust" >> /home/miluski/QuantumTrust/deploy.sh &&
            echo "git checkout main" >> /home/miluski/QuantumTrust/deploy.sh &&
            echo "git stash" >> /home/miluski/QuantumTrust/deploy.sh &&
            echo "git pull" >> /home/miluski/QuantumTrust/deploy.sh &&
            echo "docker compose up --build --force-recreate -d" >> /home/miluski/QuantumTrust/deploy.sh &&
            echo "echo Deployment made successfully" >> /home/miluski/QuantumTrust/deploy.sh &&
            chmod +x /home/miluski/QuantumTrust/deploy.sh
          fi
        '

    - name: Deploy to Server
      if: always()
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '/home/miluski/QuantumTrust/deploy.sh'